---
- name: Install node_exporter block
  block:
  - name: Create node-exporter directory
    file:
      path: "{{ container_volume }}"
      state: directory
      mode: '0755'

  - name: Create node-exporter promfiles directory
    file:
      path: "{{ container_volume }}promfiles"
      state: directory
      mode: '0755'

  - name: Copy node-exporter's docker compose files
    template:
      src: "{{ container_name }}.j2"
      dest: "{{ container_yml }}"
      mode: '0600'
  vars:
    container_name: node-exporter
  when: install_ne == True

- name: Copy cadvisor's docker compose files
  template:
    src: "{{ container_name }}.j2"
    dest: "{{ container_yml }}" 
    mode: '0600'
  vars:
    container_name: cadvisor
  when: install_cadvisor == True
