---
- name: Create directory
  file:
    path: "{{ container_volume }}"
    state: directory
    mode: '0755'

- name: Copy files
  copy:
    src: nginx.conf
    dest: "{{ container_volume }}"

- name: Copy docker-compose files
  template:
    src: tirade2.j2
    dest: "{{ container_yml }}"
    mode: '0600'
