---
- name: Create logs directory
  file:
    path: /var/log/journal
    state: directory
  register: dir

- name: Create tmpfiles
  command: systemd-tmpfiles --create --prefix /var/log/journal
  when: dir.changed

- name: Set SystemMaxUse
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^[\s#]*SystemMaxUse='
    line: "SystemMaxUse={{ journal_size }}"
  notify:
    - restart journald
